version: '3'
services:
  # frontend:
  #   build: ./ts-sanbox
  #   ports:
  #    - "8081:80"
  #   develop:
  #     watch:
  #       - action: sync
  #         path: ./ts-sandbox
  #         target: /usr/src/app
  #         ignore: 
  #           - ./ts-sandobx/node-modules
  #       - action: rebuild
  #         path: ./ts-sandbox/package.json

  # backend:
  #   build: ./api
  #   ports:
  #     - "8080:80"

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=rootpassword
    ports:
      - "8888:8081"

volumes:
  mongodb_data_container:
